export const GET_ALL_USERS_REQUESTED = 'GET_ALL_USERS_REQUESTED';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const GET_USER_REQUESTED = 'GET_USER_REQUESTED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const ADD_USER_REQUESTED = 'ADD_USER_REQUESTED';
export const ADD_USER_SUCCESS = 'ADD_USERS_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USERS_FAILED';

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

// export const GET_MSGS_REQUESTED = 'GET_MSGS_REQUESTED';
// export const GET_MSGS_SUCCESS = 'GET_MSGS_SUCCESS';
// export const GET_MSGS_FAILED = 'GET_MSGS_FAILED';

// export const ADD_MSG_REQUESTED = 'ADD_MSG_REQUESTED';
// export const ADD_MSG_SUCCESS = 'ADD_MSG_SUCCESS';
// export const ADD_MSG_FAILED = 'ADD_MSG_FAILED';
